#!/bin/bash
python generate.py --outdir=/home/anhn/TARgan/generated_images/viewmaker_diffaugment_cifar10/0 --seeds=1-1000 --network=/home/anhn/TARgan/DiffAugment-stylegan2-pytorch/training-runs/cifar-10/00005-cifar10-cond-cifar-color-translation-cutout/network-snapshot-005040.pkl --class 0 
python generate.py --outdir=/home/anhn/TARgan/generated_images/viewmaker_diffaugment_cifar10/1 --seeds=1-1000 --network=/home/anhn/TARgan/DiffAugment-stylegan2-pytorch/training-runs/cifar-10/00005-cifar10-cond-cifar-color-translation-cutout/network-snapshot-005040.pkl --class 1
python generate.py --outdir=/home/anhn/TARgan/generated_images/viewmaker_diffaugment_cifar10/2 --seeds=1-1000 --network=/home/anhn/TARgan/DiffAugment-stylegan2-pytorch/training-runs/cifar-10/00005-cifar10-cond-cifar-color-translation-cutout/network-snapshot-005040.pkl --class 2
python generate.py --outdir=/home/anhn/TARgan/generated_images/viewmaker_diffaugment_cifar10/3 --seeds=1-1000 --network=/home/anhn/TARgan/DiffAugment-stylegan2-pytorch/training-runs/cifar-10/00005-cifar10-cond-cifar-color-translation-cutout/network-snapshot-005040.pkl --class 3
python generate.py --outdir=/home/anhn/TARgan/generated_images/viewmaker_diffaugment_cifar10/4 --seeds=1-1000 --network=/home/anhn/TARgan/DiffAugment-stylegan2-pytorch/training-runs/cifar-10/00005-cifar10-cond-cifar-color-translation-cutout/network-snapshot-005040.pkl --class 4
python generate.py --outdir=/home/anhn/TARgan/generated_images/viewmaker_diffaugment_cifar10/5 --seeds=1-1000 --network=/home/anhn/TARgan/DiffAugment-stylegan2-pytorch/training-runs/cifar-10/00005-cifar10-cond-cifar-color-translation-cutout/network-snapshot-005040.pkl --class 5
python generate.py --outdir=/home/anhn/TARgan/generated_images/viewmaker_diffaugment_cifar10/6 --seeds=1-1000 --network=/home/anhn/TARgan/DiffAugment-stylegan2-pytorch/training-runs/cifar-10/00005-cifar10-cond-cifar-color-translation-cutout/network-snapshot-005040.pkl --class 6
python generate.py --outdir=/home/anhn/TARgan/generated_images/viewmaker_diffaugment_cifar10/7 --seeds=1-1000 --network=/home/anhn/TARgan/DiffAugment-stylegan2-pytorch/training-runs/cifar-10/00005-cifar10-cond-cifar-color-translation-cutout/network-snapshot-005040.pkl --class 7
python generate.py --outdir=/home/anhn/TARgan/generated_images/viewmaker_diffaugment_cifar10/8 --seeds=1-1000 --network=/home/anhn/TARgan/DiffAugment-stylegan2-pytorch/training-runs/cifar-10/00005-cifar10-cond-cifar-color-translation-cutout/network-snapshot-005040.pkl --class 8
python generate.py --outdir=/home/anhn/TARgan/generated_images/viewmaker_diffaugment_cifar10/9 --seeds=1-1000 --network=/home/anhn/TARgan/DiffAugment-stylegan2-pytorch/training-runs/cifar-10/00005-cifar10-cond-cifar-color-translation-cutout/network-snapshot-005040.pkl --class 9
